services:
  - type: web
    name: project-management-system-cohort1
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
